### PR TITLE
Get Android building again (PlatformColors)

### LINKED ISSUE #6918: react-native-paper is red screening on android
```
Render Error
Looks like you forgot to wrap your root component with Provider component from react-native-paper
Please read our getting-started guide and make sure you've followed all the required steps.
https://callstack.github.io/react-native-paper/getting-started.html
```

### LINKED ISSUE #6919: android crashes due to PlatformColor
Android docs
- https://developer.android.com/reference/android/R.attr
- https://developer.android.com/reference/android/R.color

Material docs
- https://m3.material.io/styles/color/the-color-system/tokens
- https://mui.com/material-ui/customization/color/

React native docs
- https://reactnative.dev/docs/platformcolor
- https://github.com/facebook/react-native/blob/0.71-stable/packages/rn-tester/js/examples/PlatformColor/PlatformColorExample.js

For each platformcolor, we need to define an equivalent in colors.xml and do PlatformColor(“systemBackground”, “@androidWhatecer/systemBackground”).

Otherwise we try to look up “systemBackground” in colors.xml, which doesn’t exist. Workaround while debugging is to edit colors.xml or colors/Platform.ts and provide a default (black or white).

---

Related PRs:
- #6989

### LINKED ISSUE #6990: Android building hours shows a red screen with `borderColor`
This looks self induced by the changes in #6989 (PlatformColor changes)

- ❌  If we try to use an android `PlatformColor`, we get a red screen in the `<OutllineBadge />` where `borderColor: c.separator` is used in the building hours row.
- ✅ If we use a hex string (which breaks types), the screen renders without error.

Prerequisites:
1. Overlay the changes from #6989 to prevent crashing
2. Tap building hours

```
Error while updating prop borderColor
java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.Integer
```

### LINKED ISSUE #7017: Handle google play tasks
Submit already-completed privacy policy updates (closes #6890)

### PR DESCRIPTION
**Pull request by drewvolz**
Fixes android crash on launch caused by PlatformColor adoption.

[Best viewed without whitespace and as combined](https://github.com/StoDevX/AAO-React-Native/pull/6989/files?diff=unified&w=1)

1. Fixes crashing across the Android app
2. Fixes crash for PaperProvider
2. Adds a few colors that pull from android native colors
    - text: label, secondary label, tertiary label
    - colors: red, yellow, green
    - fills: clear
3. Falls back to a light backgrounds (texts, etc)
4. Falls back to a dark foregrounds (fills, backgrounds)

```[tasklist]
### Tasks
- [x] Fix building hours badge colors
- [x] Closes #6919
- [x] Closes #6990
- [x] Closes #7017
- [x] Closes #6918
- [x] `tsc` issues introduced by wrapping colors in `Platform.select` ([see comment below](https://github.com/StoDevX/AAO-React-Native/pull/6989#issuecomment-1526568966))
```

### CODE REVIEW

**Comment by drewvolz** [comment]
Looks like wrapping with `Platform.select` changes the return signature to possibly undefined for `building-hours/color-helpers` unless a default case is provided for `systemGreen`, `systemRed`, and `label` .

```
Error: source/views/building-hours/lib/color-helpers.ts(5,2): error TS2322: Type 'OpaqueColorValue | undefined' is not assignable to type 'ColorValue'.
  Type 'undefined' is not assignable to type 'ColorValue'.
Error: source/views/building-hours/lib/color-helpers.ts(6,2): error TS2322: Type 'OpaqueColorValue | undefined' is not assignable to type 'ColorValue'.
Error: source/views/building-hours/lib/color-helpers.ts(10,2): error TS2322: Type 'OpaqueColorValue | undefined' is not assignable to type 'ColorValue'.
Error: source/views/building-hours/lib/color-helpers.ts(11,2): error TS2322: Type 'OpaqueColorValue | undefined' is not assignable to type 'ColorValue'.
Error: Process completed with exit code 2.
```

**Comment by drewvolz** [comment]
Added fallback colors to red, green, and label which are pulled out in color-helpers for building hours to make tsc happy.

File: modules/colors/platform.ts [hunk 1]
```diff
@@ -21,6 +21,7 @@ const TEMP_ANDROID_PLACEHOLDER = PlatformColor('?attr/colorAccent')
 export const label = Platform.select({
 	ios: PlatformColor('label'),
 	android: TEMP_ANDROID_PLACEHOLDER,
+	default: TEMP_ANDROID_PLACEHOLDER,
```
Comment (drewvolz) [inline modules/colors/platform.ts]: This doesn't feel like the right solution because we wouldn't want a fallback on any color definition to begin with; a fallback shouldn't need need to exist in the color definitions but the type returned from `Platform.select` produces a possibly undefined typing.

The alternative I see is to provide a guarantee or type change in `building-hours/lib/color-helpers` when the foreground and background colors are referenced.

**Comment by drewvolz** [comment]
I want to try and solve defining these colors in a consistent way. This package may be worth looking into. https://github.com/klarna-incubator/platform-colors

**Review by rye — APPROVED** [review]
