### PR TITLE
Ignore specific proptype warning for react markdown

### LINKED ISSUE #3328: Ignore specific PropTypes warning in YellowBox
there's way to have YellowBox ignore specific warnings by way of string matching.

we should ignore the following warning: 

```
Warning: Failed prop type: Invalid prop `containerTagName` of type `object` supplied to `ReactMarkdown`, expected `function`
```

derived from #3260

### PR DESCRIPTION
**Pull request by drewvolz**
Closes #3328

### CODE REVIEW

File: source/root.js [hunk 1]
```diff
@@ -3,6 +3,6 @@
 import {AppRegistry, YellowBox} from 'react-native'
 import App from './app'
 
-YellowBox.ignoreWarnings([])
+YellowBox.ignoreWarnings(['Invalid prop `containerTagName`'])
```
Comment (hawkrives) [inline source/root.js]:
```suggestion
YellowBox.ignoreWarnings([
  'Failed prop type: Invalid prop `containerTagName` of type `object` supplied to `ReactMarkdown`, expected `function`',
])
```

I want to be as specific as possible with this error silencing.

I think it does some substring matching, which is why `Invalid prop` matched `Failed prop type: Invalid prop`, but I'd rather be specific.

**Review by hawkrives — DISMISSED** [review]
(also you can do a single-to-multiline suggestion now, but I don't think you do a multi-to-single yet)

**Review by hawkrives — APPROVED** [review]
