### PR TITLE
[stoPrint]: Fix pull-to-refresh bug and fix loading states

### LINKED ISSUE #2826: [stoPrint] Visual bug in pull-to-refresh on Print Jobs screen
When I pull-to-refresh, as soon as the refresh vibration happens, my screen jumps down about twice as far as it was right before the refresh started.

screenrecording_08-20-2018 07-48-56 min

(Apologies for the gigantic gif.)

### PR DESCRIPTION
**Pull request by hannesmcman**
Resolves #2826, #2855.
This PR resolves the pull-to-refresh bug by moving the loading status of the print jobs and the list of printers from Redux state to the state of the components themselves. This also allows us to distinguish between the loading state of these components when they are first mounted vs. when they have been refreshed via pull-to-refresh. This distinction allows us to present a `<LoadingView/>` only on the initial data load, while all data requests initiated by pull-to-refresh will lead to the expected behavior (with the loading icon above the SectionList or ScrollView itself). 

Bug | Before | After
-- | -- | --
#2826 | before-2 | after-2
#2855 | before | after

### CODE REVIEW

**Review by hawkrives — COMMENTED** [review]
Just to be absolutely sure that it works, and is waiting until the whole redux action is done, could you stick a `delay(5000)` into one of the redux actions and re-test, please? I'm trying to make sure that the `await` waits for the whole function, and not just, like, the time it takes to return the inner function.

**Comment by hannesmcman** [comment]
@hawkrives Just tested it with the delay and it works (the loading is not set to false until the Redux state change is complete). However, since both of these views will always start in a loading state, I'm going to change the initial loading state of each of them to true.

File: source/views/stoprint/components/notice.js [hunk 1]
```diff
@@ -34,9 +34,7 @@ export class StoPrintNoticeView extends React.PureComponent<Props, State> {
 	}
 
 	componentDidMount() {
-		if (this._timer) {
```
Comment (hawkrives) [inline source/views/stoprint/components/notice.js:37]: good catch 👍

**Review by hawkrives — APPROVED** [review]
