### PR TITLE
Handle getting HTML from BonApp when we expected JSON

### LINKED ISSUE #1884: Handle unexpected HTML when requesting menus from BonApp
I don't know what HTML it's returning, but `JSON Parse error: Unrecognized token '<'` means that we're getting HTML instead of JSON.

We've gotten 233 of these errors in the last week, fwiw, across both wifi and cell connections.

### PR DESCRIPTION
**Pull request by hawkrives**
Closes https://github.com/StoDevX/AAO-React-Native/issues/1884 (or ameliorates it at least)

---

I made two main changes here:

1. I check to see if we're handling the "json parse error unexpected token <" error and special-case it if we are
2. I added [`p-retry`](https://www.npmjs.com/package/p-retry) to do exponential backoff and retry the menu fetch up to three times before giving up – given that we see this error right after network changes, I figure that giving it some more time to reconnect would probably fix this

I also don't report the error to bugsnag/google anymore. We could if we wanted to, I guess. I can't decide if I want to or not.

Screenshot of the new error screen:

screen shot 2017-11-18 at 6 31 29 pm

Edit: I updated the screenshot

### CODE REVIEW

File: source/views/menus/menu-bonapp.js [hunk 1]
```diff
@@ -83,19 +86,28 @@ export class BonAppHostedMenu extends React.PureComponent<Props, State> {
...
-        fetchJsonQuery(bonappMenuBaseUrl, {cafe: props.cafeId}),
-        fetchJsonQuery(bonappCafeBaseUrl, {cafe: props.cafeId}),
+        retry(this.requestMenu(props.cafeId), {retries: 3}),
+        retry(this.requestCafe(props.cafeId), {retries: 3}),
       ])
     } catch (error) {
-      tracker.trackException(error.message)
-      bugsnag.notify(error)
-      this.setState(() => ({error}))
+      if (error.message === "JSON Parse error: Unrecognized token '<'") {
```
Comment (drewvolz) [inline source/views/menus/menu-bonapp.js:110]: Could there ever be any other type of unrecognized token other than `<` we'd want to check for? Perhaps the comparison could be for "JSON Parse error:"

File: source/views/menus/menu-bonapp.js [hunk 2]
```diff
@@ -83,19 +86,28 @@ export class BonAppHostedMenu extends React.PureComponent<Props, State> {
...
+
   fetchData = async (props: Props) => {
     let cafeMenu: ?MenuInfoType = null
     let cafeInfo: ?CafeInfoType = null
 
     try {
       ;[cafeMenu, cafeInfo] = await Promise.all([
-        fetchJsonQuery(bonappMenuBaseUrl, {cafe: props.cafeId}),
-        fetchJsonQuery(bonappCafeBaseUrl, {cafe: props.cafeId}),
+        retry(this.requestMenu(props.cafeId), {retries: 3}),
```
Comment (drewvolz) [inline source/views/menus/menu-bonapp.js:106]: Is there a way for us to present a button of sorts to allow them to physically push "retry" instead of expecting them to switch the tab twice?

File: source/views/menus/menu-bonapp.js (hunk 1 above)
Comment (hawkrives) [reply source/views/menus/menu-bonapp.js:110]: I know what `<` signifies. Other errors I would like to handle separately.

File: source/views/menus/menu-bonapp.js (hunk 2 above)
Comment (hawkrives) [reply source/views/menus/menu-bonapp.js:106]: … I was thinking they'd just go back to the homescreen.

Anyway. I (a) don't want a button because that's a bigger undertaking than I wanted to do here, and (b) because if we've tried three times and it's still failing, then I think we'll have other problems (the backoff starts at 1000ms).

So I don't think a button would help, and I don't really want to put it in right now. 😸

Comment (drewvolz) [reply source/views/menus/menu-bonapp.js:106]: My beef is that you've instructed them to try again.

File: source/views/menus/menu-bonapp.js (hunk 1 above)
Comment (drewvolz) [reply source/views/menus/menu-bonapp.js:110]: Ok.

File: source/views/menus/menu-bonapp.js (hunk 2 above)
Comment (hawkrives) [reply source/views/menus/menu-bonapp.js:106]: Fair. I still don't think that a button is beneficial here, given the error conditions in which I expect this screen to appear.

Perhaps I will come around later. Who knows.

Comment (hawkrives) [reply source/views/menus/menu-bonapp.js:106]: so uh… `NoticeView` supports a button and callback already. I'll … just go use that.

Comment (drewvolz) [reply source/views/menus/menu-bonapp.js:106]: I think that was what I had in mind and was hinting towards 😄

**Review by drewvolz — APPROVED** [review]
Nice work!
