### PR TITLE
Fixed multiple settings menus

### LINKED ISSUE #155: Settings button can be pushed multiple times
> It is weirdly possible to hit the settings button quickly enough to summon multiple instances of the settings menu. They appear to be pushed onto the view stack. I can mash the mutton 4 or 5 times, and  become stuck in that state and cannot pop-back. If you push another view (credits/privacy/legal) you can get it to let you pop the settings view.

I'm thinking … disable the settings button after a tap?

But why does it take so long to open?

Hmm.

(oh lol drew suggested disabling the button too. it's a stopgap fix, at least.)

### PR DESCRIPTION
**Pull request by drewvolz**
This prevents the settings button from being mashed quickly which results in pushing two or more views to the stack. This closes #155.

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -135,19 +135,27 @@ const styles = StyleSheet.create({
   },
 })
 
+let settingsButtonActive = false
```
Comment (hawkrives) [inline app.js]: Make this a state variable in App, and pass it into the LeftButtom function as a prop.

Comment (hawkrives) [inline app.js]: Along with a callback to a member function in App to toggle the variable.

File: app.js [hunk 2]
```diff
@@ -135,19 +135,27 @@ const styles = StyleSheet.create({
...
         <TouchableOpacity
           style={[styles.backButton]}
-          onPress={() => navigator.push({
-            id: 'SettingsView',
-            title: 'Settings',
-            index: route.index + 1,
-            sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
-          })}
+          onPress={settingsButtonActive ? () => {} : () => {
+            settingsButtonActive = true
```
Comment (hawkrives) [inline app.js]: Then call that callback here

File: app.js [hunk 3]
```diff
@@ -135,19 +135,27 @@ const styles = StyleSheet.create({
...
       return (
         <TouchableOpacity
           style={[styles.backButton]}
-          onPress={() => navigator.push({
-            id: 'SettingsView',
-            title: 'Settings',
-            index: route.index + 1,
-            sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
-          })}
+          onPress={settingsButtonActive ? () => {} : () => {
```
Comment (hawkrives) [inline app.js]: You might also name the noop function, since we're naming the other.

File: app.js [hunk 4]
```diff
@@ -157,7 +165,10 @@ function LeftButton(route, navigator, index, navState) {
       return (
         <TouchableOpacity
           style={[styles.backButton, {marginLeft: 10, marginVertical: Platform.OS === 'android' ? 21 : 16}]}
-          onPress={() => navigator.pop()}
+          onPress={() => {
+            navigator.pop()
+            settingsButtonActive = false
```
Comment (hawkrives) [inline app.js]: This online function should probably be extracted to a member function,`closeSettingsScreen` or something.

**Review by hawkrives — DISMISSED** [review]

**Comment by drewvolz** [comment]
From chatting with you, this sounds as if it will be a more complicated fix than we first imagined.

File: app.js (hunk 3 above)
Comment (hawkrives) [inline app.js]: Import `noop` from lodash and use it here, and move the `settingsButtonActive = true` line into the `openSettings` function.

`onPress={settingsButtonActive ? noop : () => openSettings(route, navigator)}`

File: app.js (hunk 4 above)
Comment (hawkrives) [reply app.js]: This is still a comment I'd like to have addressed.

**Review by hawkrives — CHANGES_REQUESTED** [review]
Moar feedbacks

File: app.js (hunk 1 above)
Comment (hawkrives) [inline app.js]: Ignore these

File: app.js (hunk 3 above)
Comment (hawkrives) [reply app.js]: Ignore this comment

File: app.js (hunk 2 above)
Comment (hawkrives) [reply app.js]: Ignore this comment

File: app.js [hunk 5]
```diff
@@ -146,16 +148,18 @@ function openSettings(route, navigator) {
   })
 }
 
+function closeSettings() {
+  navigator.pop()
+  settingsButtonActive = false
```
Comment (hawkrives) [inline app.js:152]: Flip these?

File: app.js [hunk 6]
```diff
@@ -146,16 +148,18 @@ function openSettings(route, navigator) {
...
   switch (route.id) {
     case 'HomeView':
       return (
         <TouchableOpacity
           style={[styles.backButton]}
-          onPress={settingsButtonActive ? () => {} : () => {
-            settingsButtonActive = true
-            openSettings(route, navigator)
-          }}
+          onPress={settingsButtonActive ? noop : () => openSettings(route, navigator)}
```
Comment (hawkrives) [inline app.js:162]: ✅

File: app.js [hunk 7]
```diff
@@ -166,8 +170,7 @@ function LeftButton(route, navigator, index, navState) {
         <TouchableOpacity
           style={[styles.backButton, {marginLeft: 10, marginVertical: Platform.OS === 'android' ? 21 : 16}]}
           onPress={() => {
-            navigator.pop()
-            settingsButtonActive = false
+            closeSettings()
           }}
```
Comment (hawkrives) [inline app.js]: Almost

We need to give `navigator` to the function

`onPress={() => closeSettings(navigator)}`

File: app.js (hunk 5 above)
Comment (hawkrives) [reply app.js:152]: It also needs to accept `navigator` as a prop

**Review by hawkrives — CHANGES_REQUESTED** [review]
Almost there

File: app.js [hunk 8]
```diff
@@ -157,7 +169,9 @@ function LeftButton(route, navigator, index, navState) {
       return (
         <TouchableOpacity
           style={[styles.backButton, {marginLeft: 10, marginVertical: Platform.OS === 'android' ? 21 : 16}]}
-          onPress={() => navigator.pop()}
+          onPress={() => {
```
Comment (hawkrives) [inline app.js]: put this on one line and remove the outer set of braces?

File: app.js [hunk 9]
```diff
@@ -135,19 +136,30 @@ const styles = StyleSheet.create({
...
+    id: 'SettingsView',
+    title: 'Settings',
+    index: route.index + 1,
+    sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
+  })
+}
+
+function closeSettings(navigator) {
+  navigator.pop()
+  settingsButtonActive = false
```
Comment (hawkrives) [inline app.js:152]: and should we flip these two?

I don't think there'll be any functional difference

File: app.js (hunk 8 above)
Comment (drewvolz) [reply app.js]: Sure

File: app.js (hunk 5 above)
Comment (drewvolz) [reply app.js:152]: Done.

File: app.js (hunk 9 above)
Comment (drewvolz) [reply app.js:152]: We could.

**Review by hawkrives — APPROVED** [review]
